### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by iconara**
This replaces #45 and #47 and can be applied to both master and v1.2.x. It runs all tests with warnings enabled, and also removes all causes for warnings except one (see below).

In JRuby warnings are printed from WEBrick when running an SSL server. This issue has been fixed in jruby/jruby-openssl#110 so we'll just have to live with those warnings until the next jruby-openssl version is released.

### CODE REVIEW

**Comment by iconara** [comment]
@eprothro can you verify that this does what you wanted? I realised that it was quicker to just do this myself than arguing.

**Comment by eprothro** [comment]
@iconara yes, this look great thanks.

**Comment by iconara** [comment]
This was merged into the v1.2.x branch in ee1957fede01cff5aa0fcd3de13c6ba1c6c69427 and into master in 611ee8d335575a58e655536b28770e140aefdb61.

**Comment by eprothro** [comment]
@iconara FYI, the jRuby SSL warnings went away for me when I included the `spec_helper` from the `.rspec` file. That unhid another warning (coverall not being able to get complete coverage from jRuby tracing) that was fixed with the `.jrubyrc` that I added.

**Comment by iconara** [comment]
I'm not sure which JRuby you tested with, but the `.jrubyrc` you added crashed JRuby as soon as it started for me and Travis (using JRuby 1.7.19).

**Comment by eprothro** [comment]
I was testing with 9.1.5 locally. 

I hadn't dug into it yet, but I had an impression that the jruby crashes were due to the bundler changes, not the .jrubyrc. Were those changes coupled when it crashed for you, or was that just with the .jrubyrc?

**Comment by iconara** [comment]
This has been released as [v1.2.4](https://github.com/iconara/ione/releases/tag/v1.2.4)

**Comment by iconara** [comment]
Adding a `.jrubyrc` with `debug.fullTrace=true` crashes JRuby 1.7.19 in this branch. Running with `-Xdebug.fullTrace=true` has the same effect so it's definitely that.

**Comment by iconara** [comment]
Adding a `.jrubyrc` with `debug.fullTrace=true` crashes JRuby 1.7.19 in this branch. Running with `-Xdebug.fullTrace=true` has the same effect so it's definitely that.

**Comment by eprothro** [comment]
@iconara yeah, I just saw the same thing with 1.7 locally.

**Pull request merged**
