### PR TITLE
fixup ruby warnings (1.3.x - master)

### PR DESCRIPTION
**Pull request by eprothro**
Warnings patch from #45 applied to master.

### CODE REVIEW

**Comment by eprothro** [comment]
extra commit in with merge, fixing now.

**Comment by eprothro** [comment]
@iconara Do you feel these are ready for merge? If so, would you consider a 1.2.4 release?

**Comment by iconara** [comment]
@eprothro as I said in #45 there are still warnings printed in JRuby.

**Comment by eprothro** [comment]
@iconara warnings fixed. before I squash these last few bundler issues for 13ea0227300a9e7fee63c0fdca979ccf9c0fdacd, are you positive for that change?

**Comment by iconara** [comment]
I commented on the removal of `Gemfile.lock` in #45. You can make that suggestion separately. Please stick to the topic of these PRs and not make changes to the structure of this project.

**Comment by iconara** [comment]
Closing in favour of #48

**Pull request closed without merging**
